config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"

  devise_for :users,controllers: { sessions: 'users/sessions' }

  resources :users

  resources :messages




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'

    # # 物理削除の代わりにユーザーの`deleted_at`をタイムスタンプで更新
    # def soft_delete  
    #   update_attribute(:deleted_at, Time.current)  
    # end
  
    # ユーザーのアカウントが有効であることを確認 
    def active_for_authentication?
     super && deleted_at.nil?
    end
  
    # # 削除したユーザーにカスタムメッセージを追加します  
    # def inactive_message   
    #   !deleted_at ? super : :deleted_account  
    # end 
      

    
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
  
end

app/controllers/users/sessions_controller.rb
# # frozen_string_literal: true

# class Users::SessionsController < Devise::SessionsController 
#  # < DeviseController
#  prepend_before_action :require_no_authentication, only: [:new, :create]
#  prepend_before_action :allow_params_authentication!, only: :create
#  prepend_before_action :verify_signed_out_user, only: :destroy
#  prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }

#  # GET /resource/sign_in
#  def new
#   binding.b
#    self.resource = resource_class.new(sign_in_params)
#    clean_up_passwords(resource)
#    yield resource if block_given?
#    respond_with(resource, serialize_options(resource))
#  end

#  # POST /resource/sign_in
#  def create
#    self.resource = warden.authenticate!(auth_options)
#    set_flash_message!(:notice, :signed_in)
#    sign_in(resource_name, resource)
#    yield resource if block_given?
#    respond_with resource, location: after_sign_in_path_for(resource)
#  end

class Users::SessionsController < Devise::SessionsController
 # POST /resource/sign_in
 def create
  binding.b
   self.resource = warden.authenticate!(auth_options)
   if resource.deleted_at.nil?
    flash[:notice] = 'アカウント有効ですよー。'
     set_flash_message!(:notice, :signed_in)
     sign_in(resource_name, resource)
     yield resource if block_given?
     respond_with resource, location: after_sign_in_path_for(resource)
   else
    puts "テストデバッグ"
     flash[:alert] = "アカウントは無効ですよー。"
     redirect_to new_user_session_path
   end
 end
end


#  # DELETE /resource/sign_out
#  def destroy
#    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
#    set_flash_message! :notice, :signed_out if signed_out
#    yield if block_given?
#    respond_to_on_destroy
#  end

#  protected

#  def sign_in_params
#    devise_parameter_sanitizer.sanitize(:sign_in)
#  end

#  def serialize_options(resource)
#    methods = resource_class.authentication_keys.dup
#    methods = methods.keys if methods.is_a?(Hash)
#    methods << :password if resource.respond_to?(:password)
#    { methods: methods, only: [:password] }
#  end

#  def auth_options
#    { scope: resource_name, recall: "#{controller_path}#new", locale: I18n.locale }
#  end

#  def translation_scope
#    'devise.sessions'
#  end

#  private

#  # Check if there is no signed in user before doing the sign out.
#  #
#  # If there is no signed in user, it will set the flash message and redirect
#  # to the after_sign_out path.
#  def verify_signed_out_user
#    if all_signed_out?
#      set_flash_message! :notice, :already_signed_out

#      respond_to_on_destroy
#    end
#  end

#  def all_signed_out?
#    users = Devise.mappings.keys.map { |s| warden.user(scope: s, run_callbacks: false) }

#    users.all?(&:blank?)
#  end

#  def respond_to_on_destroy
#    # We actually need to hardcode this as Rails default responder doesn't
#    # support returning empty response on GET request
#    respond_to do |format|
#      format.all { head :no_content }
#      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: Devise.responder.redirect_status }
#    end
#  end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

#   def index
#    @users = User.where(deleted_at: nil)
# end
  

def create
 binding.b
  self.resource = warden.authenticate!(auth_options)
  if resource.deleted_at.nil?
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  else
    flash.now[:alert] = "アカウントは無効ですよー。"
    redirect_to new_user_session_path
  end
end


  def show
    @user = User.find(params[:id])
    sent_messages = current_user.sent_messages.where(recipient_id: params[:id])
    received_messages = @user.sent_messages.where(recipient_id: current_user.id)
    if current_user.id == @user.id
      @messages = sent_messages
    elsif
      @messages = (sent_messages + received_messages).sort_by(&:created_at)
    end
  end

  # def destroy
  #   user = User.find(params[:id])
  #   if user.id == current_user.id && user.destroy
  #     flash[:notice] = "アカウント削除に成功しました"
  #     redirect_to new_user_registration_path
  #   else
  #     flash[:notice] = "無効な操作です。アカウント削除はできません。"
  #     redirect_to user_path
  #   end
  # end

  # def destroy
  #  user = User.find(params[:id])
  #   if user.id == current_user.id && user.update(deleted_at: Time.now)
  #     flash[:notice] = "アカウント削除に成功しました"
  #     redirect_to root_path
  #   else
  #     flash[:notice] = "無効な操作です。アカウント削除はできません。"
  #     redirect_to user_path
  #   end
  # end

  def update
   user = User.find(params[:id])
   # user = User.where.not(deleted_at: nil).where(id: params[:id]).first
   # or
   # binding.b
   # user = User.where.not(deleted_at: nil).find_by(id: params[:id])
    if user.id == current_user.id && user.update(deleted_at: Time.now)
      sign_out(:user)
      flash[:notice] = "アカウント削除に成功しました"
      redirect_to root_path
    else
      flash[:notice] = "無効な操作です。アカウント削除はできません。"
      redirect_to user_path
    end
  end

end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="element">
    <% @users.each do |user| %>
      <div class="user">
        <%= link_to user_path(user) do %>
          <div class="name"><%= user.name %>
          <% if user.id != current_user.id%>  
            <%= link_to "ユーザーへメッセージ", user_path(user), class: "text-white" %>
          <% elsif user.id == current_user.id %>
            <%= link_to "メモ", user_path(user), class: "text-white" %>
          <% end %>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-container">
  <% if current_page?(user_path) %>
    <%= render 'layouts/show_header' %>
      <% if @user.id == current_user.id %>
        <p class="d-flex justify-content-end">
          <%= link_to "プロフィール編集", edit_user_registration_path(@user), class: "btn-sm btn-success" %>
        </p>
      <% end %>
  <% end %>

  <main class="show-main">
      <%= @user.name %>
      <% @messages.each do |msg| %>
        <% if msg.sender_id == current_user.id %>
          <div style="text-align: right;">
            <%= msg.sender_id %>
            <%= msg.recipient_id %>
            <%= current_user.name%>
            <%= msg.message %>
            <br>
            <%= msg.created_at%>
            <br>
            <%= link_to "編集", edit_message_path(msg.id), class: "btn btn-primary" %>
            <%= button_to "削除", message_path(msg.id), method: :delete, data: { turbo_confirm: "本当に削除しますか?" }, class: "btn btn-primary" %>
          </div>
        <% elsif msg.sender_id == @user.id %>
          <div style="text-align: left;">
            <%= msg.sender_id %>
            <%= msg.recipient_id %>
            <%= msg.message %>
            <br>
            <%= msg.created_at%>
            <br>
          </div>
        <% end %>
      <% end %>
  </main>

  <footer class="show-footer">
    <div>
    <%= form_with url: messages_path do |f| %>
      <p>message</p>
      <%= f.text_area :message %></br>
      <%= f.hidden_field :recipient_id, value: params[:id] %>

      <%= f.submit '送信'%>
    <% end %>
    </div>
  </footer>
</div>