config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"

  devise_for :users,controllers: { sessions: 'users/sessions' }

  resources :users

  resources :messages




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
    <header>
      <div class="header_container">
        <% if user_signed_in? %>
            <div><%= link_to "#{current_user.name}", user_path(current_user.id), class: "text-white" %></div>
            <div class="top" ><%= link_to "ホーム", root_path, class: "text-white" %></div>
            <div class="user_all"><%= link_to "ユーザー一覧", users_path, class: "text-white" %></div>
            <div class="logout"><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %></div>
        <% else %>
            <div class="signup"><%= link_to "サインアップ", new_user_registration_path, class: "text-white" %></div>
            <div class="login"><%= link_to "ログイン", new_user_session_path, class: "text-white" %></div>
        <% end %> 
          <div class="main">
            <% flash.each do |key, value| %>
                <p class="alert alert-<%= key %>">
                  <%= value %>
                </p>
            <% end %>
          </div>
      </div>
    </header> 

app/views/layouts/_show_header.html.erb
    <header>
      <div class="show_header">
        <% if user_signed_in? %>
            <div><%= link_to "#{current_user.name}", edit_user_registration_path(@user), class: "text-white" %></div>
            <div><%= link_to "トップ", root_path, class: "text-white" %></div>
            <div><%= link_to "ユーザー一覧", users_path, class: "text-white" %></div>
            <div><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %></div>
            <% if @user.id == current_user.id %>
              <p class="d-flex justify-content-end">
                <div><%= button_to "アカウント削除", user_path(current_user.id), method: :patch, data: { turbo_confirm: "本当に削除しますか?" }, class: "text-white" %></div>
              </p>
            <% end %>
        <% else %>
            <div><%= link_to "サインアップ", new_user_registration_path, class: "text-white" %></div>
            <div><%= link_to "ログイン", new_user_session_path, class: "text-white" %></div>
        <% end %> 

          <div class="main">
            <% flash.each do |key, value| %>
                <p class="alert alert-<%= key %>">
                  <%= value %>
                </p>
            <% end %>
        </div>
      </div>
    </header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if request.path == "/users/#{params[:id]}" %>
    <% else %>
      <%= render partial: "layouts/header" %>
    <% end %>


        <%= yield %>
        

  </body>
</html>